services:
    armory:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./data:/data/
            - ./logs:/logs/
        env_file:
            - .env
        networks:
            - local-private-net
        ports:
            - 48733:48733

networks:
    local-private-net:
        driver: bridge
    ac-network:
        name: ${DOCKER_AC_NETWORK_NAME:-azerothcore-wotlk_ac-network} # default network name if you use the docker setup of ac
        external: ${DOCKER_AC_NETWORK_EXTERNAL:-false}
